#ifndef ARCADIA_STATUS_H
#define ARCADIA_STATUS_H

typedef enum _ARCADIA_status
{
	ARCADIA_STATUS_OK = 0,
	ARCADIA_STATUS_FAILED,
	ARCADIA_STATUS_API_TIMEOUT,
	//////////
	ARCADIA_STATUS_NUM_STATUSES
} ARCADIA_status_t;

#endif // ARCADIA_STATUS_H
