#ifndef CLOCK_H
#define CLOCK_H

#include "includes.h"


typedef enum
{
	CLOCK_GCLOCK_ID_0 = GCLK_CLKCTRL_GEN_GCLK0_Val,
	CLOCK_GCLOCK_ID_1 = GCLK_CLKCTRL_GEN_GCLK1_Val,
	CLOCK_GCLOCK_ID_2 = GCLK_CLKCTRL_GEN_GCLK2_Val,
	CLOCK_GCLOCK_ID_3 = GCLK_CLKCTRL_GEN_GCLK3_Val,
	CLOCK_GCLOCK_ID_4 = GCLK_CLKCTRL_GEN_GCLK4_Val,
	CLOCK_GCLOCK_ID_5 = GCLK_CLKCTRL_GEN_GCLK5_Val,
	CLOCK_GCLOCK_ID_6 = GCLK_CLKCTRL_GEN_GCLK6_Val,
	CLOCK_GCLOCK_ID_7 = GCLK_CLKCTRL_GEN_GCLK7_Val,
	CLOCK_GCLOCK_ID_8 = GCLK_CLKCTRL_GEN_GCLK8_Val,
	//
	CLOCK_GCLOCK_ID_NUM_GCLOCKS
} CLOCK_gclock_id;

typedef enum
{
	CLOCK_SOURCE_XOSC 		= GCLK_GENCTRL_SRC_XOSC_Val,
	CLOCK_SOURCE_GCLKIN 	= GCLK_GENCTRL_SRC_GCLKIN_Val,
	CLOCK_SOURCE_GCLKGEN1 	= GCLK_GENCTRL_SRC_GCLKGEN1_Val,
	CLOCK_SOURCE_OSCULP32K 	= GCLK_GENCTRL_SRC_OSCULP32K_Val,
	CLOCK_SOURCE_OSC32K 	= GCLK_GENCTRL_SRC_OSC32K_Val,
	CLOCK_SOURCE_XOSC32K 	= GCLK_GENCTRL_SRC_XOSC32K_Val,
	CLOCK_SOURCE_OSC8M 		= GCLK_GENCTRL_SRC_OSC8M_Val,
	CLOCK_SOURCE_DFLL48M 	= GCLK_GENCTRL_SRC_DFLL48M_Val,
	CLOCK_SOURCE_DPLL96M 	= GCLK_GENCTRL_SRC_DPLL96M_Val,
	//
	CLOCK_SOURCE_NUM_SOURCES
} CLOCK_source_t;

void CLOCK_osc8m_init	(void);
void CLOCK_gclock_init	(const CLOCK_gclock_id gclock, const CLOCK_source_t source);

#endif