#ifndef ARCADIA_TASK_H
#define ARCADIA_TASK_H

typedef enum _ARCADIA_task_id
{
	ARCADIA_TASK_ID_SHELL = 0,
	ARCADIA_TASK_ID_DRIVE,
	ARCADIA_TASK_ID_CHRONO,
	//////////
	ARCADIA_TASK_ID_NUM_IDS
} ARCADIA_task_id_t;

#endif // ARCADIA_TASK_H