#ifndef VERSION_H
#define VERSION_H


#define VERSION_MAJOR			(0)
#define VERSION_MINOR			(3)
#define VERSION_PATCH			(0)

#define VERSION_FREERTOS 			"202406.01-LTS"
#define VERSION_PART_ATSAMC21E18A 	"ATSAMC21E18A"
#define VERSION_PART_ATSAMC21N18A 	"ATSAMC21N18A"

#ifdef AUDIO_SWITCH
#define VERSION_PROJECT_NAME		"Audio Switch"
#define VERSION_PART				VERSION_PART_ATSAMC21E18A
#endif // AUDIO_SWITCH

#ifdef DEV_BOARD
#define VERSION_PROJECT_NAME		"Dev Board"
#define VERSION_PART				VERSION_PART_ATSAMC21E18A
#endif // DEV_BOARD

#ifdef JLINK_MUX
#define VERSION_PROJECT_NAME		"JLink Mux"
#define VERSION_PART				VERSION_PART_ATSAMC21N18A
#endif // JLINK_MUX

#endif // VERSION_H
